IMAGE_SIZE: [224, 224, 3] 
BATCH_SIZE: 8
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 15
WEIGHTS: imagenet
LEARNING_RATE: 0.001
COLOR_MODE: rgb
CLASS_MODE: categorical
OPTIMIZER: adam
TEST_RATIO: 0.2
HORIZONTAL_FLIP: False
ZOOM_RANGE: 0
W_SHIFT: 0
H_SHIFT: 0
ROTATION_RANGE: 0
SHEAR_RANGE: 0
FILL_ZEROS: False